### ISSUE TITLE
Setup Repo with CircleCI

### ISSUE THREAD

**Issue by jakobkolb** [hardforkio/todos#2]
Config is there, but Admin needs to set it up. @Levino

**Comment by Levino** [comment]
I set it up. Is this still an issue or will you delete this repo?

**Comment by jakobkolb** [comment]
I have not decided this yet. I feel like continuing on this at some point but also, this point may never come.

**Comment by Levino** [comment]
Send yourself an email with heading: "Delete hardforkio/todos" and put it on Wiedervorlage in two weeks from now. Then you will not forget.

**Comment by Levino** [comment]
Repo is setup, closing.
